steps:
# Step 1: Restore pip cache
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: restore-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp gs://${_PROJECT_ID}-build-cache/consolidator-pip-cache.tar.gz pip-cache.tar.gz || echo "Cache not found."
    if [ -f pip-cache.tar.gz ]; then
      tar -xzf pip-cache.tar.gz
    fi

# Step 2: Install dependencies using the cache
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: pip-install
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install --cache-dir=./.pip_cache -r requirements.txt
  waitFor: ['restore-cache']

# Step 3: Save the updated cache
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: save-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    tar -czf pip-cache.tar.gz ./.pip_cache
    gsutil cp pip-cache.tar.gz gs://${_PROJECT_ID}-build-cache/consolidator-pip-cache.tar.gz
  waitFor: ['pip-install']

# Step 4: Build and Push the image
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: build-and-push
  entrypoint: 'docker'
  args:
  - 'build'
  - '--tag'
  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID'
  - '--tag'
  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'
  - '.'
  waitFor: ['save-cache']

- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: push
  entrypoint: 'docker'
  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}', '--all-tags']
  waitFor: ['build-and-push']

# Step 5: Download tfvars and Deploy
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: deploy
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret="consolidator-tfvars" --project="${_PROJECT_ID}" > terraform/terraform.tfvars
    cd terraform
    terraform init -backend-config="prefix=cloud-spanner-demo/${_PROJECT_SUFFIX}/consolidator"
    terraform apply -auto-approve -var="image_tag=$BUILD_ID"
  waitFor: ['push']

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID'
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: '${PROJECT_ID}'
  _LOCATION: 'europe-west1'
  _REPOSITORY_ID: 'my-docker-repo'
  _IMAGE_NAME: 'graphrag-fn-consolidator'
  _PROJECT_SUFFIX: '' # This will be overridden by the trigger
