steps:
# Step 1: Restore cached packages
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: restore-cache
  entrypoint: bash
  args:
  - -c
  - |
    gsutil cp gs://${_PROJECT_ID}-build-cache/consolidator-packages.tar.gz packages.tar.gz || echo "Cache not found."
    if [ -f packages.tar.gz ]; then
      mkdir -p ./packages
      tar -xzf packages.tar.gz -C ./packages
    fi

# Step 2: Install/update packages into the local 'packages' directory
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: pip-install
  entrypoint: bash
  args:
  - -c
  - |
    pip install --target=./packages --upgrade --break-system-packages -r requirements.txt
  waitFor: ['restore-cache']

# Step 3: Save the updated packages to the cache
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: save-cache
  entrypoint: bash
  args:
  - -c'
  - |
    tar -czf packages.tar.gz -C ./packages .
    gsutil cp packages.tar.gz gs://${_PROJECT_ID}-build-cache/consolidator-packages.tar.gz
  waitFor: ['pip-install']

# Step 4: Build and Push the image
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: build-and-push
  entrypoint: bash
  args:
  - -c
  - |
    docker build --tag '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID' --tag '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest' .
    docker push '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}' --all-tags
  waitFor: ['save-cache']

# Step 5: Download config and deploy
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: deploy
  entrypoint: sh
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret="consolidator-tfvars" --project="${_PROJECT_ID}" > terraform/terraform.tfvars
    cd terraform
    terraform init -backend-config="prefix=cloud-spanner-demo/${_PROJECT_SUFFIX}/consolidator"
    terraform apply -auto-approve -var="image_tag=$BUILD_ID"
  waitFor: ['build-and-push']

# Step 6: Clean up old images
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: cleanup-images
  entrypoint: bash
  args:
  - './cleanup_images.sh'
  - '${_LOCATION}'
  - '${_PROJECT_ID}'
  - '${_REPOSITORY_ID}'
  - '${_IMAGE_NAME}'
  waitFor: ['deploy']

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID'
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: '${PROJECT_ID}'
  _LOCATION: 'europe-west1'
  _REPOSITORY_ID: 'my-docker-repo'
  _IMAGE_NAME: 'graphrag-fn-consolidator'
  _PROJECT_SUFFIX: '' # This will be overridden by the trigger
